# Check https://circleci.com/docs/2.0/language-javascript/ for more details

defaults: &defaults
  docker:
    # specify the version you desire here
    - image: circleci/node:8

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      # 加速缓存，提高速度
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - package.json
            - README.md
            - LICENSE
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn ci
      #- run: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: test-results
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      # 设置之后 用npm的token就可以不用登陆直接publish
      - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run: npm publish

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - prepare
      - build:
          requires:
            - test
      - test:
          requires:
            - prepare
      - publish:
          requires:
            - build
          # circle tag filters 对每次git push进行过滤，仅当添加tag的时候进行发布的操作
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
            # 分支提交不会导致publish
            branches:
              only: master
